### ISSUE TITLE
Default profile for commands outside of normal profiles

### ISSUE THREAD

**Issue by andyshinn** [gliderlabs/glidergun#11]
There are occasions where you might want to have commands inside profiles, but also others that don't belong under profiles. Consider a project which uses two profiles to work with different providers (`.gun_digitalocean` and `.gun_aws`). You might want command outside of these namespaces as well such as `gun build` and `gun start`, but others under the profile, `gun aws provision`.

**Comment by progrium** [comment]
now in master
