### ISSUE TITLE
gun.bash appending .gun to .gitignore should verify file ends with EOL

### ISSUE THREAD

**Issue by rliebling** [gliderlabs/glidergun#5]
the part of gun.bash that appends ".gun" to the .gitignore file didn't work correctly for me, because my .gitignore file did not end with an EOL.  So, the resulting file ended with this line

```
.DS_Store.gun
```

**Comment by progrium** [comment]
Ran into this as well last night.

**Comment by progrium** [comment]
Fixed in just released 0.0.5 ... you can just re-install with install instructions. Future updates can be done with `gun update`.
